---
- hosts: client2 
  become: true
  become_user: root
  tasks: 
  - name: Install WGET 
    yum: name=wget state=installed 

  - name: Install Python-mysqldb 
    yum: name=MySQL-python state=installed 

  - name: Create folder 
    file: path=/opt/mysql state=directory
  
  - name: Download sources
    get_url: 
      url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm 
      dest: /opt/mysql

  - name: Install package 
    yum: 
      name: /opt/mysql/mysql-community-release-el7-5.noarch.rpm 
      state: present
 
  - name: Install MySQL 
    yum: name=mysql-server state=installed 

  - name: MySQL is up and running
    become: true 
    service: 
      name: mysqld 
      state: restarted
      enabled: true
 
  - name: Create a User 
    mysql_user: user=varshini password=varshini priv='*.*:ALL,GRANT' state=present 
 
  - name: Create a Database 
    mysql_db: name=assignment4 state=present
 
  - name: Adding  database dump file to remote machine 
    copy: src=/etc/ansible/dump.sql dest=/tmp
 
  - name: Import data into database 
    mysql_db: name=assignment4 state=import target=/tmp/dump.sql
 
  - name: restart mysql 
    service: name=mysql state=restarted

  - name: execute output file script
    shell: echo "select * from AUTOMATION limit 3" | mysql -uvarshini -pvarshini assignment4 > /home/ec2-user/output.txt
   


 
  
  ##- debug: var=out.stdout_lines

